import type { Metadata } from "next";
import type { Viewport } from 'next';
import localFont from "next/font/local";
import ".././styles/globals.css";
import Header from "@/components/header"

const museoSans = localFont({
  src: ".././fonts/Museo/MuseoSansCyrl-100.ttf",
  variable: "--font-museo-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width',
  maximumScale: 1,
  userScalable: false
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={museoSans.variable}>
      <body className={`bg-black text-white ${museoSans.className} overflow-x-hidden`}>
        <div className="flex flex-col min-h-screen">
          <Header/>
          <main className="flex-grow overflow-auto">
              {children}
          </main>
          <footer className="grid grid-cols-2 p-4">
          {[["+7-800-555-35-35","youremail@mail.com","Адрес: Ханты-Мансийский автономный округ — Югра, г Ханты-Мансийск, ул Анны Коньковой, д 1"].map((item) => (
            <p className="text-sm m-2">{item}</p>
          ))]}
          </footer>
        </div>
      </body>
    </html>
  );
}