import type { Metadata } from "next";
import localFont from "next/font/local";
import ".././styles/globals.css";
import Header from "@/components/header"

const museoSans = localFont({
  src: ".././fonts/Museo/MuseoSansCyrl-100.ttf",
  variable: "--font-museo-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={museoSans.variable}>
      <body className={`bg-black text-white ${museoSans.className}`}>
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow">
            <div className="container mx-auto px-4 py-8">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}